[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_counter = "CjX5PnXQf48ogjjBZpYqcmamzbhqjQxXXf7B9WmvJyXa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/webclues/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
